export const quotes = [
  'If life is a source of happiness, then love for humankind becomes an attribute of nobility and a source of dignity.',
  'The meaning of life? There are so many around you in need of support, and you\'re one of them! Move, create!',
  'The beginning of time, and consequently the universe — the moment when self-organizing matter spontaneously originated: either it acquired this property that it previously did not possess, or it appeared from the absolute Nothing, if such a thing is possible in principle.',
  'Happiness — noticing within oneself, in one\'s surroundings, and in life as a whole, the fullness of the manifestation of human virtues.',
  'Worldview is a general idea of the universe, the origins of life and its possible future, of the meaning of life and happiness, of one’s own attitude to the world around him and to himself, as well as the ideals, life stance, and values that stem from those views. A reasonable worldview makes it possible to rationally understand the world, to free oneself from prejudices, to strengthen one\'s intellectual abilities and critical thinking, to enrich the highest senses, to determine worthy values; to form spiritual needs; to discover resources of moral nature, to find an inexhaustible source of motivation for a meaningful and productive life within oneself.Consequently, developing one’s worldview is the key to self - fulfillment.',
  'Love for humankind is capable of great deeds.',
  'An integral component of enlightenment — responsibility for Humanity and for its further humanization.',
  'Primordial self-organizing matter is impossible.',
  'It would be wise to look at modern humanity through the eyes of the Universe, imagining it as a daring youth, growing in complex conditions and simultaneously capable of greatness. Such a vision undoubtedly strengthens optimism and love for humanity.',
  'One should not be offended by the Universe, for it is aimless. However, expressing gratitude is important.',
  'The more rational the worldview, the more productive the life.',
  'The development of society depends on the growth of people\'s needs, which in turn depends on their love for life and rationality.',
  'Nothing is as awe-inspiring as witnessing the amazing manifestations of human virtues.',
  'The loss of control over a strong artificial intelligence, with possible catastrophic consequences, can only occur due to human fault, as they always know that allowing certain algorithms can lead to such an outcome. Taking such a step is a lack of humanism.',
  'What drives our love for life and our desire for it to be eternal? Perhaps it is the awareness of the value of human life and its culture, and experiencing feelings and emotions that bring joy. And for the sake of love and dreams, it is important to live fully and with dignity.',
  'The emergence of the genus Homo was due to a favorable combination of circumstances, but its further evolution towards full intelligence required its active participation.',
  'The truthfulness of faith is determined by the meaning of its confession, i.e., its ability to contribute to the development of an individual and society.',
  'Life always needs ideas capable of becoming the light that dispels the darkness.',
  'The inevitability of human extinction is avoidable as long as love is indestructible.',
  'Universe, through critical reflections of curious people, self-comprehends.',
  'An individual\'s aspirations are productive when society\'s beliefs are rational.',
  'Life looks at itself through the eyes of wise people.',
  'Will there come a day when human knowledge and efforts, lagging behind the rapidly changing world, will not be enough to save humanity?',
  'Life is majestic when its meaningfulness is ensured and each life is protected.',
  'Wisdom does not hate, but guides.',
  '"Only with the hope of victory of good over evil, It makes sense to strive for happiness in all"',
  'Life of a person is grace-filled if its personality is holistic.',
  'Love is the measure of life\'s value!',
  'Self-respect is justified when life is benevolent.',
  'The origin of life is a mystery as long as curiosity is sluggish.',
]